# Agglomerative Clustering



 این الگوریتم با هدف تحلیل شخصیتی مشتری وتقسیم بندی انها برای بازاریابی بهتر برای کارکنان و سرمایه داران طراحی شده است. داده شامل اطلاعاتی از قبیل  درآمد مشتری , تعداد فرزندان مشتری,سال تولد و... را شامل میشود.

This algorithm is designed to analyze customer personality and segment them for better marketing for employees and investors. The data includes information such as customer income, number of children, year of birth, and so on.



 توجه توضیح یسری از سلول ها اگر وجود نداره در فایل

music.ipynb
 هست


 Note: Some of the explanations or cells may be missing here, but they are available in the file `music.ipynb`.

In [24]:
import pandas as pd
import numpy as np
import scipy
import matplotlib.cm as cm
import matplotlib.pyplot as plt
import  matplotlib.pylab as pylab

دیتا از:https://www.kaggle.com/code/karnikakapoor/customer-segmentation-clustering
~~~ Data

In [25]:
x=pd.read_csv('marketing_campaign.csv')
x

ID  Year_Birth   Education Marital_Status   Income  Kidhome  \
0      5524        1957  Graduation         Single  58138.0        0   
1      2174        1954  Graduation         Single  46344.0        1   
2      4141        1965  Graduation       Together  71613.0        0   
3      6182        1984  Graduation       Together  26646.0        1   
4      5324        1981         PhD        Married  58293.0        1   
...     ...         ...         ...            ...      ...      ...   
2235  10870        1967  Graduation        Married  61223.0        0   
2236   4001        1946         PhD       Together  64014.0        2   
2237   7270        1981  Graduation       Divorced  56981.0        0   
2238   8235        1956      Master       Together  69245.0        0   
2239   9405        1954         PhD        Married  52869.0        1   

      Teenhome  Recency  MntWines  MntFruits  ...  NumWebVisitsMonth  \
0            0       58       635         88  ...                  7   
1            1       38        11          1  ...                  5   
2            0       26       426         49  ...                  4   
3            0       26        11          4  ...                  6   
4            0       94       173         43  ...                  5   
...        ...      ...       ...        ...  ...                ...   
2235         1       46       709         43  ...                  5   
2236         1       56       406          0  ...                  7   
2237         0       91       908         48  ...                  6   
2238         1        8       428         30  ...                  3   
2239         1       40        84          3  ...                  7   

      AcceptedCmp3  AcceptedCmp4  AcceptedCmp5  AcceptedCmp1  AcceptedCmp2  \
0                0             0             0             0             0   
1                0             0             0             0             0   
2                0             0             0             0             0   
3                0             0             0             0             0   
4                0             0             0             0             0   
...            ...           ...           ...           ...           ...   
2235             0             0             0             0             0   
2236             0             0             0             1             0   
2237             0             1             0             0             0   
2238             0             0             0             0             0   
2239             0             0             0             0             0   

      Complain  Z_CostContact  Z_Revenue  Response  
0            0              3         11         1  
1            0              3         11         0  
2            0              3         11         0  
3            0              3         11         0  
4            0              3         11         0  
...        ...            ...        ...       ...  
2235         0              3         11         0  
2236         0              3         11         0  
2237         0              3         11         0  
2238         0              3         11         0  
2239         0              3         11         1  

[2240 rows x 28 columns]

In [26]:
x.isnull().sum()

ID                      0
Year_Birth              0
Education               0
Marital_Status          0
Income                 24
Kidhome                 0
Teenhome                0
Recency                 0
MntWines                0
MntFruits               0
MntMeatProducts         0
MntFishProducts         0
MntSweetProducts        0
MntGoldProds            0
NumDealsPurchases       0
NumWebPurchases         0
NumCatalogPurchases     0
NumStorePurchases       0
NumWebVisitsMonth       0
AcceptedCmp3            0
AcceptedCmp4            0
AcceptedCmp5            0
AcceptedCmp1            0
AcceptedCmp2            0
Complain                0
Z_CostContact           0
Z_Revenue               0
Response                0
dtype: int64

In [27]:
x=x.dropna()
x

ID  Year_Birth   Education Marital_Status   Income  Kidhome  \
0      5524        1957  Graduation         Single  58138.0        0   
1      2174        1954  Graduation         Single  46344.0        1   
2      4141        1965  Graduation       Together  71613.0        0   
3      6182        1984  Graduation       Together  26646.0        1   
4      5324        1981         PhD        Married  58293.0        1   
...     ...         ...         ...            ...      ...      ...   
2235  10870        1967  Graduation        Married  61223.0        0   
2236   4001        1946         PhD       Together  64014.0        2   
2237   7270        1981  Graduation       Divorced  56981.0        0   
2238   8235        1956      Master       Together  69245.0        0   
2239   9405        1954         PhD        Married  52869.0        1   

      Teenhome  Recency  MntWines  MntFruits  ...  NumWebVisitsMonth  \
0            0       58       635         88  ...                  7   
1            1       38        11          1  ...                  5   
2            0       26       426         49  ...                  4   
3            0       26        11          4  ...                  6   
4            0       94       173         43  ...                  5   
...        ...      ...       ...        ...  ...                ...   
2235         1       46       709         43  ...                  5   
2236         1       56       406          0  ...                  7   
2237         0       91       908         48  ...                  6   
2238         1        8       428         30  ...                  3   
2239         1       40        84          3  ...                  7   

      AcceptedCmp3  AcceptedCmp4  AcceptedCmp5  AcceptedCmp1  AcceptedCmp2  \
0                0             0             0             0             0   
1                0             0             0             0             0   
2                0             0             0             0             0   
3                0             0             0             0             0   
4                0             0             0             0             0   
...            ...           ...           ...           ...           ...   
2235             0             0             0             0             0   
2236             0             0             0             1             0   
2237             0             1             0             0             0   
2238             0             0             0             0             0   
2239             0             0             0             0             0   

      Complain  Z_CostContact  Z_Revenue  Response  
0            0              3         11         1  
1            0              3         11         0  
2            0              3         11         0  
3            0              3         11         0  
4            0              3         11         0  
...        ...            ...        ...       ...  
2235         0              3         11         0  
2236         0              3         11         0  
2237         0              3         11         0  
2238         0              3         11         0  
2239         0              3         11         1  

[2216 rows x 28 columns]

In [28]:
x=x.drop('ID',axis=1)
x

Year_Birth   Education Marital_Status   Income  Kidhome  Teenhome  \
0           1957  Graduation         Single  58138.0        0         0   
1           1954  Graduation         Single  46344.0        1         1   
2           1965  Graduation       Together  71613.0        0         0   
3           1984  Graduation       Together  26646.0        1         0   
4           1981         PhD        Married  58293.0        1         0   
...          ...         ...            ...      ...      ...       ...   
2235        1967  Graduation        Married  61223.0        0         1   
2236        1946         PhD       Together  64014.0        2         1   
2237        1981  Graduation       Divorced  56981.0        0         0   
2238        1956      Master       Together  69245.0        0         1   
2239        1954         PhD        Married  52869.0        1         1   

      Recency  MntWines  MntFruits  MntMeatProducts  ...  NumWebVisitsMonth  \
0          58       635         88              546  ...                  7   
1          38        11          1                6  ...                  5   
2          26       426         49              127  ...                  4   
3          26        11          4               20  ...                  6   
4          94       173         43              118  ...                  5   
...       ...       ...        ...              ...  ...                ...   
2235       46       709         43              182  ...                  5   
2236       56       406          0               30  ...                  7   
2237       91       908         48              217  ...                  6   
2238        8       428         30              214  ...                  3   
2239       40        84          3               61  ...                  7   

      AcceptedCmp3  AcceptedCmp4  AcceptedCmp5  AcceptedCmp1  AcceptedCmp2  \
0                0             0             0             0             0   
1                0             0             0             0             0   
2                0             0             0             0             0   
3                0             0             0             0             0   
4                0             0             0             0             0   
...            ...           ...           ...           ...           ...   
2235             0             0             0             0             0   
2236             0             0             0             1             0   
2237             0             1             0             0             0   
2238             0             0             0             0             0   
2239             0             0             0             0             0   

      Complain  Z_CostContact  Z_Revenue  Response  
0            0              3         11         1  
1            0              3         11         0  
2            0              3         11         0  
3            0              3         11         0  
4            0              3         11         0  
...        ...            ...        ...       ...  
2235         0              3         11         0  
2236         0              3         11         0  
2237         0              3         11         0  
2238         0              3         11         0  
2239         0              3         11         1  

[2216 rows x 27 columns]

In [29]:
# x=np.asanyarray(x)

In [30]:
from sklearn.preprocessing import LabelEncoder

lb=LabelEncoder()
x['Education']=lb.fit_transform(x['Education'])


lb2=LabelEncoder()
x['Marital_Status']=lb2.fit_transform(x['Marital_Status'])

In [31]:
from sklearn.preprocessing import MinMaxScaler
sc=MinMaxScaler()
x=sc.fit_transform(x)
x

array([[0.62135922, 0.5       , 0.57142857, ..., 0.        , 0.        ,
        1.        ],
       [0.59223301, 0.5       , 0.57142857, ..., 0.        , 0.        ,
        0.        ],
       [0.69902913, 0.5       , 0.71428571, ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.85436893, 0.5       , 0.28571429, ..., 0.        , 0.        ,
        0.        ],
       [0.61165049, 0.75      , 0.71428571, ..., 0.        , 0.        ,
        0.        ],
       [0.59223301, 1.        , 0.42857143, ..., 0.        , 0.        ,
        1.        ]], shape=(2216, 27))

In [32]:
from sklearn.decomposition import PCA
pca=PCA(n_components=2)
x=pca.fit_transform(x)
x

array([[ 0.74887008,  0.30531189],
       [-0.53869989,  0.11122599],
       [ 0.23751754, -0.30500341],
       ...,
       [ 0.47438195, -0.4563821 ],
       [ 0.18941389, -0.30715032],
       [-0.05427714,  0.78489996]], shape=(2216, 2))

In [33]:
from sklearn.metrics.pairwise import euclidean_distances
dist_matrix = euclidean_distances(x,x)
print(dist_matrix)

[[0.         1.30211588 0.79621994 ... 0.8096428  0.82951865 0.93544117]
 [1.30211588 0.         0.88077263 ... 1.16125525 0.83975497 0.82976022]
 [0.79621994 0.88077263 0.         ... 0.28110542 0.04815154 1.12828786]
 ...
 [0.8096428  1.16125525 0.28110542 ... 0.         0.32167829 1.3491707 ]
 [0.82951865 0.83975497 0.04815154 ... 0.32167829 0.         1.11890979]
 [0.93544117 0.82976022 1.12828786 ... 1.3491707  1.11890979 0.        ]]


In [34]:
from sklearn.cluster import AgglomerativeClustering
cluster_n=4
model=AgglomerativeClustering(linkage='average',n_clusters=cluster_n).fit(x)
print(model.labels_)

[1 0 0 ... 0 0 2]


In [35]:
label_ll=model.labels_
label_ll

array([1, 0, 0, ..., 0, 0, 2], shape=(2216,))



در این قسمت خوشه بندی نمره خوبی دریافت نکرده است وضعیف عمل کرده است.

"In this clustering section, it has not received a good score and has performed poorly.

In [36]:
from sklearn.metrics import silhouette_score
silhouette_score(x, label_ll)


0.43545029699535504


در اینجا هم مدل عملکرد خوبی نداشته و نمره پایینی دریافت کرده.

here too, the model has not performed well and has received a low score.

In [38]:
from sklearn.metrics import davies_bouldin_score

davies_bouldin_score(x, label_ll)

0.6696462734315035


برخلاف دو معیار ارزیابی فوق، این مدل در جداسازی خوشه‌ها عملکرد بسیار خوبی داشته و امتیاز خوبی دریافت کرده است.

Unlike the two evaluation metrics above, the model has performed excellently in keeping clusters apart and has received a good score.

In [39]:
from sklearn.metrics import calinski_harabasz_score

calinski_harabasz_score(x, label_ll)

763.6971050854825



بطور کلی , مدل عالی عمل نکرده است و تنها درجداسازی خوشه ها خوب عمل کرده.

overall, the model has not performed excellently and has only done well in separating the clusters.